export { default as AlmacenLayout } from './shared/AlmacenLayout';
export { default as AlmacenIndexRedirect } from './shared/AlmacenIndexRedirect';
export * from './productos';
export * from './proveedores';
export * from './maestros';
export * from './ingresos';
export * from './stock';
export * from './despachos';
export * from './custodia';
export * from './pedidos';
export * from './transferencias';
export * from './ajustes';
export * from './ordenes-compra';
export * from './shared/sede.store';
export * from './shared/types';
export * from './shared/almacen.api';
